const { DataTypes, Model } = require('sequelize');
const dbServer = require('../../../config/connections/db_server_raw');

class EMSData extends Model { }

EMSData.init({
    id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
    incident_number: { type: DataTypes.STRING(255), allowNull: true },
    notification_time: { type: DataTypes.DATE, allowNull: true },
    province_code: { type: DataTypes.STRING(255), allowNull: true },
    center_code: { type: DataTypes.STRING(255), allowNull: true },
    district: { type: DataTypes.STRING(255), allowNull: true },
    sub_district: { type: DataTypes.STRING(255), allowNull: true },
    latitude: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    longitude: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    scene_location: { type: DataTypes.STRING(255), allowNull: true },
    severity_code: { type: DataTypes.STRING(255), allowNull: true },
    incident_event: { type: DataTypes.STRING(255), allowNull: true },
    patient_number: { type: DataTypes.STRING(255), allowNull: true },
    ipd_event_number: { type: DataTypes.STRING(255), allowNull: true },
    id_card_number: { type: DataTypes.STRING(255), allowNull: true },
    patient_sequence: { type: DataTypes.STRING(255), allowNull: true },
    patient_id: { type: DataTypes.STRING(255), allowNull: true },
    title: { type: DataTypes.STRING(255), allowNull: true },
    first_name: { type: DataTypes.STRING(255), allowNull: true },
    last_name: { type: DataTypes.STRING(255), allowNull: true },
    gender: { type: DataTypes.STRING(255), allowNull: true },
    age_years: { type: DataTypes.STRING(255), allowNull: true },
    age_months: { type: DataTypes.STRING(255), allowNull: true },
    patient_type: { type: DataTypes.STRING(255), allowNull: true },
    nationality: { type: DataTypes.STRING(255), allowNull: true },
    passport_number: { type: DataTypes.STRING(255), allowNull: true },
    treatment_right: { type: DataTypes.STRING(255), allowNull: true },
    other_insurance: { type: DataTypes.STRING(255), allowNull: true },
    country: { type: DataTypes.STRING(255), allowNull: true },
    vehicle_type: { type: DataTypes.STRING(255), allowNull: true },
    vehicle_plate_category: { type: DataTypes.STRING(255), allowNull: true },
    vehicle_plate_number: { type: DataTypes.STRING(255), allowNull: true },
    vehicle_province: { type: DataTypes.STRING(255), allowNull: true },
    delivery_province: { type: DataTypes.STRING(255), allowNull: true },
    hospital: { type: DataTypes.STRING(255), allowNull: true },
    hospital_type: { type: DataTypes.STRING(255), allowNull: true },
    delivery_time: { type: DataTypes.STRING(255), allowNull: true },
    triage_level: { type: DataTypes.STRING(255), allowNull: true },
    operation_number: { type: DataTypes.STRING(255), allowNull: true },
    operation_event_number: { type: DataTypes.STRING(255), allowNull: true },
    command_time: { type: DataTypes.STRING(255), allowNull: true },
    unit_level: { type: DataTypes.STRING(255), allowNull: true },
    time_unit_notified: { type: DataTypes.STRING(255), allowNull: true },
    time_left_base: { type: DataTypes.STRING(255), allowNull: true },
    lat_left_base: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    long_left_base: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    time_arrived_scene: { type: DataTypes.STRING(255), allowNull: true },
    time_left_scene: { type: DataTypes.STRING(255), allowNull: true },
    lat_scene: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    long_scene: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    time_arrived_hospital: { type: DataTypes.STRING(255), allowNull: true },
    lat_hospital: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    long_hospital: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    time_arrived_base: { type: DataTypes.STRING(255), allowNull: true },
    lat_base: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    long_base: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    idc_code_scene: { type: DataTypes.TEXT, allowNull: true },
    operation_status: { type: DataTypes.TEXT, allowNull: true },
    operation_option: { type: DataTypes.TEXT, allowNull: true },
    vehicle_plate_cat_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    vehicle_plate_num_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    vehicle_province_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    vehicle_owner_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    system_status: { type: DataTypes.TEXT, allowNull: true },
    recorder_name: { type: DataTypes.TEXT, allowNull: true },
    patient_type_2: { type: DataTypes.TEXT, allowNull: true },
    consciousness: { type: DataTypes.TEXT, allowNull: true },
    breathing: { type: DataTypes.TEXT, allowNull: true },
    wound: { type: DataTypes.TEXT, allowNull: true },
    deformity: { type: DataTypes.TEXT, allowNull: true },
    organ: { type: DataTypes.TEXT, allowNull: true },
    airway: { type: DataTypes.TEXT, allowNull: true },
    stop_bleeding: { type: DataTypes.TEXT, allowNull: true },
    splinting: { type: DataTypes.TEXT, allowNull: true },
    fluids: { type: DataTypes.TEXT, allowNull: true },
    fluids_detail: { type: DataTypes.TEXT, allowNull: true },
    cpr: { type: DataTypes.TEXT, allowNull: true },
    medication: { type: DataTypes.TEXT, allowNull: true },
    initial_care_result: { type: DataTypes.TEXT, allowNull: true },
    wound_2: { type: DataTypes.TEXT, allowNull: true },
    deformity_2: { type: DataTypes.TEXT, allowNull: true },
    blood_loss: { type: DataTypes.TEXT, allowNull: true },
    organ_2: { type: DataTypes.TEXT, allowNull: true },
    medicine_method: { type: DataTypes.TEXT, allowNull: true },
    medicine_detail: { type: DataTypes.TEXT, allowNull: true },
    obgyn: { type: DataTypes.TEXT, allowNull: true },
    obgyn_detail: { type: DataTypes.TEXT, allowNull: true },
    pediatrics: { type: DataTypes.TEXT, allowNull: true },
    pediatrics_detail: { type: DataTypes.TEXT, allowNull: true },
    surgery: { type: DataTypes.TEXT, allowNull: true },
    surgery_detail: { type: DataTypes.TEXT, allowNull: true },
    others: { type: DataTypes.TEXT, allowNull: true },
    diagnosis: { type: DataTypes.TEXT, allowNull: true },
    airway_2: { type: DataTypes.TEXT, allowNull: true },
    stop_bleeding_2: { type: DataTypes.TEXT, allowNull: true },
    splinting_2: { type: DataTypes.TEXT, allowNull: true },
    fluids_2: { type: DataTypes.TEXT, allowNull: true },
    admitted: { type: DataTypes.TEXT, allowNull: true },
    treatment_result: { type: DataTypes.TEXT, allowNull: true },
    vital_signs: { type: DataTypes.TEXT, allowNull: true },
    neuro_signs: { type: DataTypes.TEXT, allowNull: true },
    pupils: { type: DataTypes.TEXT, allowNull: true },
    o2_sat: { type: DataTypes.TEXT, allowNull: true },
    dtx: { type: DataTypes.TEXT, allowNull: true },
    createdAt: { type: DataTypes.DATE, allowNull: true },
    updatedAt: { type: DataTypes.DATE, allowNull: true }
}, {
    sequelize: dbServer,
    modelName: 'EMSData',
    tableName: 'ems_records',
    timestamps: true,
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    underscored: false,
    freezeTableName: true
});

module.exports = EMSData;
