const { Sequelize, DataTypes, Model } = require('sequelize');
const dbServer = require('../../config/connections/db_server');
class HisMergeData extends Model {}

HisMergeData.init({
    id: { type: DataTypes.INTEGER, allowNull: false, primaryKey: true, autoIncrement: true },
    match: { type: DataTypes.TEXT, allowNull: true },
    is_duplicate: { type: DataTypes.TINYINT, allowNull: true },
    pid: { type: DataTypes.STRING(20), allowNull: true },
    hospcode: { type: DataTypes.STRING(10), allowNull: true },
    date_serv: { type: DataTypes.DATE, allowNull: true },
    seq: { type: DataTypes.STRING(20), allowNull: true },
    an: { type: DataTypes.STRING(20), allowNull: true },
    diagcode: { type: DataTypes.STRING(10), allowNull: true },
    isdeath: { type: DataTypes.INTEGER, allowNull: true },
    cdeath: { type: DataTypes.STRING(10), allowNull: true },
    price: { type: DataTypes.FLOAT, allowNull: true },
    payprice: { type: DataTypes.FLOAT, allowNull: true },
    actualpay: { type: DataTypes.FLOAT, allowNull: true },
    dateinhosp: { type: DataTypes.FLOAT, allowNull: true },
    cid: { type: DataTypes.STRING(20), allowNull: true },
    name: { type: DataTypes.STRING(255), allowNull: true },
    lname: { type: DataTypes.STRING(255), allowNull: true },
    sex: { type: DataTypes.STRING(5), allowNull: true },
    nation: { type: DataTypes.STRING(10), allowNull: true },
    birth: { type: DataTypes.DATE, allowNull: true },
    age: { type: DataTypes.INTEGER, allowNull: true },
    opd_code: { type: DataTypes.TEXT, allowNull: true },
    ipd_code: { type: DataTypes.TEXT, allowNull: true },
    allcode: { type: DataTypes.TEXT, allowNull: true },
    s0: { type: DataTypes.INTEGER, allowNull: true },
    s1: { type: DataTypes.INTEGER, allowNull: true },
    s2: { type: DataTypes.INTEGER, allowNull: true },
    s3: { type: DataTypes.INTEGER, allowNull: true },
    s4: { type: DataTypes.INTEGER, allowNull: true },
    s5: { type: DataTypes.INTEGER, allowNull: true },
    s6: { type: DataTypes.INTEGER, allowNull: true },
    s7: { type: DataTypes.INTEGER, allowNull: true },
    s8: { type: DataTypes.INTEGER, allowNull: true },
    s9: { type: DataTypes.INTEGER, allowNull: true },
    aeplace: { type: DataTypes.STRING(5), allowNull: true },
    aetype: { type: DataTypes.STRING(5), allowNull: true },
    airway: { type: DataTypes.STRING(5), allowNull: true },
    alcohol: { type: DataTypes.STRING(5), allowNull: true },
    splint: { type: DataTypes.STRING(5), allowNull: true },
    belt: { type: DataTypes.STRING(5), allowNull: true },
    helmet: { type: DataTypes.STRING(5), allowNull: true },
    coma_eye: { type: DataTypes.STRING(5), allowNull: true },
    coma_movement: { type: DataTypes.STRING(5), allowNull: true },
    coma_speak: { type: DataTypes.STRING(5), allowNull: true },
    nacrotic_drug: { type: DataTypes.STRING(5), allowNull: true },
    stopbleed: { type: DataTypes.STRING(5), allowNull: true },
    traffic: { type: DataTypes.STRING(5), allowNull: true },
    typein_ae: { type: DataTypes.STRING(5), allowNull: true },
    urgency: { type: DataTypes.STRING(5), allowNull: true },
    vehicle: { type: DataTypes.STRING(5), allowNull: true },
    province_code: { type: DataTypes.INTEGER, allowNull: true },
    updated_at: { type: DataTypes.DATE, allowNull: true },
    old_id: { type: DataTypes.INTEGER, allowNull: true },
    created_at: { type: DataTypes.STRING(255), allowNull: true },
    project_id: { type: DataTypes.INTEGER, allowNull: true },
    project_file_id: { type: DataTypes.INTEGER, allowNull: true }
}, {
    sequelize: dbServer,
    modelName: 'HisMergeData',
    tableName: 'temp_his_query_clean',
    underscored: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at'
});

module.exports = HisMergeData;
