const { DataTypes, Model } = require('sequelize');
const dbServer = require('../../config/connections/db_server');

class IntegrateFinalFullEMS extends Model { }

IntegrateFinalFullEMS.init({
    id: { type: DataTypes.INTEGER.UNSIGNED, autoIncrement: true, primaryKey: true },
    name: { type: DataTypes.STRING(100), allowNull: true, comment: 'ชื่อ' },
    lname: { type: DataTypes.STRING(100), allowNull: true, comment: 'นามสุกล' },
    cid: { type: DataTypes.STRING(20), allowNull: true },
    admit: { type: DataTypes.INTEGER, allowNull: true },
    gender: { type: DataTypes.INTEGER, allowNull: true },
    nationality: { type: DataTypes.STRING(100), allowNull: true },
    dob: { type: DataTypes.DATEONLY, allowNull: true },
    age: { type: DataTypes.INTEGER, allowNull: true },
    injury_date: { type: DataTypes.DATEONLY, allowNull: true },
    is_death: { type: DataTypes.BOOLEAN, allowNull: true },
    occupation: { type: DataTypes.STRING(100), allowNull: true },
    hdate: { type: DataTypes.DATEONLY, allowNull: true },
    alcohol: { type: DataTypes.STRING(255), allowNull: true },
    belt_risk: { type: DataTypes.STRING(100), allowNull: true },
    helmet_risk: { type: DataTypes.STRING(100), allowNull: true },
    roaduser: { type: DataTypes.STRING(100), allowNull: true },
    vehicle_1_type: { type: DataTypes.INTEGER, allowNull: true },
    vehicle_1: { type: DataTypes.STRING(100), allowNull: true },
    vehicle_plate_1: { type: DataTypes.STRING(20), allowNull: true },
    accdate: { type: DataTypes.DATE, allowNull: true },
    atumbol: { type: DataTypes.STRING(100), allowNull: true },
    aaumpor: { type: DataTypes.STRING(100), allowNull: true },
    aaumpor_code: { type: DataTypes.INTEGER, allowNull: true },
    aprovince: { type: DataTypes.STRING(100), allowNull: true },
    aprovince_code: { type: DataTypes.INTEGER, allowNull: true },
    area_code: { type: DataTypes.INTEGER, allowNull: true },
    vehicle_2: { type: DataTypes.STRING(100), allowNull: true },
    police_event_id: { type: DataTypes.STRING(255), allowNull: true },
    hospcode: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_id: { type: DataTypes.BIGINT, allowNull: true },
    eclaim_protocal: { type: DataTypes.STRING(255), allowNull: true },
    is_id: { type: DataTypes.BIGINT, allowNull: true },
    is_protocal: { type: DataTypes.STRING(255), allowNull: true },
    his_id: { type: DataTypes.BIGINT, allowNull: true },
    his_protocal: { type: DataTypes.STRING(255), allowNull: true },
    police_id: { type: DataTypes.BIGINT, allowNull: true },
    police_protocal: { type: DataTypes.STRING(255), allowNull: true },
    alat: { type: DataTypes.FLOAT, allowNull: true },
    along: { type: DataTypes.FLOAT, allowNull: true },
    acc_province_id: { type: DataTypes.INTEGER, allowNull: true },
    his_pid: { type: DataTypes.STRING(20), allowNull: true },
    his_hospcode: { type: DataTypes.STRING(10), allowNull: true },
    his_date_serv: { type: DataTypes.DATE, allowNull: true },
    his_seq: { type: DataTypes.STRING(20), allowNull: true },
    his_an: { type: DataTypes.STRING(20), allowNull: true },
    his_diagcode: { type: DataTypes.STRING(10), allowNull: true },
    his_isdeath: { type: DataTypes.INTEGER, allowNull: true },
    his_cdeath: { type: DataTypes.STRING(10), allowNull: true },
    his_price: { type: DataTypes.FLOAT, allowNull: true },
    his_payprice: { type: DataTypes.FLOAT, allowNull: true },
    his_actualpay: { type: DataTypes.FLOAT, allowNull: true },
    his_dateinhosp: { type: DataTypes.FLOAT, allowNull: true },
    his_cid: { type: DataTypes.STRING(20), allowNull: true },
    his_name: { type: DataTypes.STRING(255), allowNull: true },
    his_lname: { type: DataTypes.STRING(255), allowNull: true },
    his_sex: { type: DataTypes.STRING(5), allowNull: true },
    his_nation: { type: DataTypes.STRING(10), allowNull: true },
    his_birth: { type: DataTypes.DATEONLY, allowNull: true },
    his_age: { type: DataTypes.INTEGER, allowNull: true },
    his_opd_code: { type: DataTypes.TEXT, allowNull: true },
    his_ipd_code: { type: DataTypes.TEXT, allowNull: true },
    his_allcode: { type: DataTypes.TEXT, allowNull: true },
    his_s0: { type: DataTypes.INTEGER, allowNull: true },
    his_s1: { type: DataTypes.INTEGER, allowNull: true },
    his_s2: { type: DataTypes.INTEGER, allowNull: true },
    his_s3: { type: DataTypes.INTEGER, allowNull: true },
    his_s4: { type: DataTypes.INTEGER, allowNull: true },
    his_s5: { type: DataTypes.INTEGER, allowNull: true },
    his_s6: { type: DataTypes.INTEGER, allowNull: true },
    his_s7: { type: DataTypes.INTEGER, allowNull: true },
    his_s8: { type: DataTypes.INTEGER, allowNull: true },
    his_s9: { type: DataTypes.INTEGER, allowNull: true },
    his_aeplace: { type: DataTypes.STRING(5), allowNull: true },
    his_aetype: { type: DataTypes.STRING(5), allowNull: true },
    his_airway: { type: DataTypes.STRING(5), allowNull: true },
    his_alcohol: { type: DataTypes.STRING(5), allowNull: true },
    his_splint: { type: DataTypes.STRING(5), allowNull: true },
    his_belt: { type: DataTypes.STRING(5), allowNull: true },
    his_helmet: { type: DataTypes.STRING(5), allowNull: true },
    his_coma_eye: { type: DataTypes.STRING(5), allowNull: true },
    his_coma_movement: { type: DataTypes.STRING(5), allowNull: true },
    his_coma_speak: { type: DataTypes.STRING(5), allowNull: true },
    his_nacrotic_drug: { type: DataTypes.STRING(5), allowNull: true },
    his_stopbleed: { type: DataTypes.STRING(5), allowNull: true },
    his_traffic: { type: DataTypes.STRING(5), allowNull: true },
    his_typein_ae: { type: DataTypes.STRING(5), allowNull: true },
    his_urgency: { type: DataTypes.STRING(5), allowNull: true },
    his_vehicle: { type: DataTypes.STRING(5), allowNull: true },
    his_old_id: { type: DataTypes.INTEGER, allowNull: true },
    his_project_id: { type: DataTypes.INTEGER, allowNull: true },
    his_project_file_id: { type: DataTypes.INTEGER, allowNull: true },
    is_ref: { type: DataTypes.INTEGER, allowNull: true },
    is_hosp: { type: DataTypes.STRING(100), allowNull: true, comment: 'รหัสโรงพยาบาล' },
    is_prov: { type: DataTypes.STRING(2), allowNull: true, comment: 'ชื่อจังหวัด' },
    is_hn: { type: DataTypes.STRING(10), allowNull: true, defaultValue: '' },
    is_an: { type: DataTypes.STRING(12), allowNull: true },
    is_titlecode: { type: DataTypes.STRING(10), allowNull: true, comment: 'รหัสคำนำหน้าชื่อ' },
    is_prename: { type: DataTypes.STRING(20), allowNull: true, comment: 'คำนำหน้าชื่อ' },
    is_name: { type: DataTypes.STRING(30), allowNull: true, defaultValue: '', comment: 'ชื่อ' },
    is_fname: { type: DataTypes.STRING(30), allowNull: true, comment: 'สกุล' },
    is_lname: { type: DataTypes.STRING(30), allowNull: true, comment: 'สกุล' },
    is_pid: { type: DataTypes.STRING(20), allowNull: true, defaultValue: '', comment: 'บัตรประชาชน หรือ Passport' },
    is_home: { type: DataTypes.CHAR(1), allowNull: true, comment: 'จังหวัดที่อยู่ 1. ในจังหวัด 2. นอกจังหวัด 3. นอกประเทศ N ไม่ทราบ' },
    is_address: { type: DataTypes.STRING(100), allowNull: true },
    is_tumbon: { type: DataTypes.STRING(2), allowNull: true },
    is_ampur: { type: DataTypes.STRING(50), allowNull: true },
    is_changwat: { type: DataTypes.STRING(50), allowNull: true },
    is_tel: { type: DataTypes.STRING(15), allowNull: true },
    is_sex: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: 1 },
    is_birth: { type: DataTypes.DATE, allowNull: true },
    is_day: { type: DataTypes.INTEGER, allowNull: true },
    is_month: { type: DataTypes.INTEGER, allowNull: true },
    is_age: { type: DataTypes.INTEGER, allowNull: true },
    is_occu: { type: DataTypes.STRING(2), allowNull: true, comment: 'อาชีพ' },
    is_occu_t: { type: DataTypes.STRING(50), allowNull: true, comment: 'อาชีพอื่นๆ' },
    is_nationality: { type: DataTypes.STRING(4), allowNull: true, defaultValue: '1', comment: 'สัญชาติ' },
    is_adate: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่เกิดเหตุ' },
    is_atime: { type: DataTypes.DATE, allowNull: true, comment: 'เวลาที่เกิดเหตุ' },
    is_hdate: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่ผู้บาดเจ็บมารับการรักษาที่โรงพยาบาล' },
    is_htime: { type: DataTypes.DATE, allowNull: true, comment: 'เวลาที่ผู้บาดเจ็บมารับการรักษาที่โรงพยาบาล' },
    is_aplace: { type: DataTypes.STRING(4), allowNull: true, defaultValue: '', comment: 'จ.ที่เกิดเหตุ' },
    is_aampur: { type: DataTypes.STRING(2), allowNull: true, comment: 'อ.ที่เกิดเหตุ' },
    is_atumbon: { type: DataTypes.STRING(2), allowNull: true, comment: 'ต.ที่เกิดเหตุ' },
    is_mooban: { type: DataTypes.STRING(50), allowNull: true },
    is_road_type: { type: DataTypes.STRING(4), allowNull: true },
    is_apoint: { type: DataTypes.STRING(3), allowNull: true, comment: 'จุดเกิดเหตุ' },
    is_apointname: { type: DataTypes.STRING(50), allowNull: true, comment: 'ระบุสถานที่เกิดเหตุ' },
    is_injby: { type: DataTypes.CHAR(1), allowNull: true, defaultValue: '', comment: 'การบาดเจ็บเกิดโดย เจตนาหรือไม่' },
    is_injoccu: { type: DataTypes.CHAR(1), allowNull: true },
    is_cause: { type: DataTypes.CHAR(1), allowNull: true, defaultValue: '', comment: 'สาเหตุของการบาดเจ็บ' },
    is_cause_t: { type: DataTypes.STRING(50), allowNull: true, defaultValue: '', comment: 'Triage' },
    is_injp: { type: DataTypes.CHAR(1), allowNull: true, comment: 'ผู้บาดเจ็บเกี่ยวข้องกับอุบัติเหตุ' },
    is_injt: { type: DataTypes.STRING(7), allowNull: true, comment: 'สัตว์ หรือพานะที่ถูกใช้ในการขนส่ง' },
    is_vehicle1: { type: DataTypes.STRING(30), allowNull: true, comment: 'ยานพาหนะ' },
    is_vehicle1_license: { type: DataTypes.STRING(20), allowNull: true, comment: 'ทะเบียนรถผู้บาดเจ็บ' },
    is_vehicle2: { type: DataTypes.STRING(30), allowNull: true, comment: 'ยานพาหนะคู่กรณี' },
    is_vehicle2_license: { type: DataTypes.STRING(20), allowNull: true, comment: 'ทะเบียนรถคู่กรณี' },
    is_injt_t: { type: DataTypes.STRING(50), allowNull: true },
    is_injfrom: { type: DataTypes.STRING(7), allowNull: true, comment: 'การบาดเจ็บเกิดจาก' },
    is_injfrom_t: { type: DataTypes.STRING(50), allowNull: true },
    is_icdcause: { type: DataTypes.STRING(50), allowNull: true, comment: 'สาเหตุของอุบัติเหตุและการบาดเจ็บตาม ICD 10' },
    is_activity: { type: DataTypes.STRING(50), allowNull: true, comment: 'กิจกรรมขณะเกิดเหตุ' },
    is_product: { type: DataTypes.STRING(50), allowNull: true, comment: 'ผลิตภัณฑ์ที่ทำให้บาดเจ็บ' },
    is_alclevel: { type: DataTypes.FLOAT(8, 2), allowNull: true },
    is_risk1: { type: DataTypes.CHAR(1), allowNull: true },
    is_risk2: { type: DataTypes.CHAR(1), allowNull: true },
    is_risk3: { type: DataTypes.CHAR(1), allowNull: true },
    is_risk4: { type: DataTypes.CHAR(1), allowNull: true },
    is_risk5: { type: DataTypes.CHAR(1), allowNull: true },
    is_risk9: { type: DataTypes.CHAR(1), allowNull: true },
    is_risk9_text: { type: DataTypes.STRING(50), allowNull: true },
    is_pmi: { type: DataTypes.CHAR(1), allowNull: true, defaultValue: '', comment: 'ผู้บาดเจ็บเสียชีวิต ณ จุดเกิดเหตุ' },
    is_atohosp: { type: DataTypes.CHAR(1), allowNull: true },
    is_ems: { type: DataTypes.STRING(2), allowNull: true, comment: 'หน่วยกู้ชีพที่ออกไปรับ' },
    is_atohosp_t: { type: DataTypes.STRING(50), allowNull: true },
    is_htohosp: { type: DataTypes.STRING(50), allowNull: true },
    is_hprov: { type: DataTypes.STRING(2), allowNull: true },
    is_amb: { type: DataTypes.CHAR(2), allowNull: true },
    is_refer: { type: DataTypes.CHAR(1), allowNull: true },
    is_airway: { type: DataTypes.CHAR(1), allowNull: true },
    is_airway_t: { type: DataTypes.STRING(50), allowNull: true },
    is_blood: { type: DataTypes.CHAR(1), allowNull: true },
    is_blood_t: { type: DataTypes.STRING(50), allowNull: true },
    is_splintc: { type: DataTypes.CHAR(1), allowNull: true },
    is_splntc_t: { type: DataTypes.STRING(50), allowNull: true },
    is_splint: { type: DataTypes.CHAR(1), allowNull: true },
    is_splint_t: { type: DataTypes.STRING(50), allowNull: true },
    is_iv: { type: DataTypes.CHAR(1), allowNull: true },
    is_iv_t: { type: DataTypes.STRING(50), allowNull: true },
    is_hxcc: { type: DataTypes.CHAR(1), allowNull: true, comment: 'สลบ' },
    is_hxcc_hr: { type: DataTypes.INTEGER, allowNull: true, comment: 'สลบ: ชม.' },
    is_hxcc_min: { type: DataTypes.INTEGER, allowNull: true, comment: 'สลบ: นาที' },
    is_bp1: { type: DataTypes.INTEGER, allowNull: true, comment: 'SBP' },
    is_bp2: { type: DataTypes.INTEGER, allowNull: true, comment: 'DBP' },
    is_bp: { type: DataTypes.STRING(3), allowNull: true, comment: 'BP' },
    is_pr: { type: DataTypes.INTEGER, allowNull: true, comment: 'Pulse' },
    is_rr: { type: DataTypes.INTEGER, allowNull: true, comment: 'RR' },
    is_e: { type: DataTypes.INTEGER, allowNull: true, comment: 'Coma eye' },
    is_v: { type: DataTypes.INTEGER, allowNull: true, comment: 'Coma Verbal' },
    is_m: { type: DataTypes.INTEGER, allowNull: true, comment: 'Coma Motor' },
    is_coma: { type: DataTypes.INTEGER, allowNull: true, comment: 'Coma Score' },
    is_tinj: { type: DataTypes.CHAR(1), allowNull: true },
    is_diser: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่จำหน่ายจาก ER' },
    is_timer: { type: DataTypes.DATE, allowNull: true, comment: 'เวลาจำหน่ายจาก ER' },
    is_er: { type: DataTypes.CHAR(1), allowNull: true },
    is_er_t: { type: DataTypes.STRING(50), allowNull: true },
    is_staer: { type: DataTypes.CHAR(1), allowNull: true, comment: 'สถานะจำหน่ายจาก ER' },
    is_ward: { type: DataTypes.STRING(4), allowNull: true, comment: 'Ward ที่ Admit' },
    is_staward: { type: DataTypes.CHAR(1), allowNull: true, comment: 'สถานะจำหน่ายจาก Ward' },
    is_diag1: { type: DataTypes.STRING(50), allowNull: true },
    is_br1: { type: DataTypes.INTEGER, allowNull: true },
    is_ais1: { type: DataTypes.INTEGER, allowNull: true },
    is_diag2: { type: DataTypes.STRING(50), allowNull: true },
    is_br2: { type: DataTypes.INTEGER, allowNull: true },
    is_ais2: { type: DataTypes.INTEGER, allowNull: true },
    is_diag3: { type: DataTypes.STRING(50), allowNull: true },
    is_br3: { type: DataTypes.INTEGER, allowNull: true },
    is_ais3: { type: DataTypes.INTEGER, allowNull: true },
    is_diag4: { type: DataTypes.STRING(50), allowNull: true },
    is_br4: { type: DataTypes.INTEGER, allowNull: true },
    is_ais4: { type: DataTypes.INTEGER, allowNull: true },
    is_diag5: { type: DataTypes.STRING(50), allowNull: true },
    is_br5: { type: DataTypes.INTEGER, allowNull: true },
    is_ais5: { type: DataTypes.INTEGER, allowNull: true },
    is_diag6: { type: DataTypes.STRING(50), allowNull: true },
    is_br6: { type: DataTypes.INTEGER, allowNull: true },
    is_ais6: { type: DataTypes.INTEGER, allowNull: true },
    is_rdate: { type: DataTypes.DATE, allowNull: true },
    is_rts: { type: DataTypes.INTEGER, allowNull: true },
    is_iss: { type: DataTypes.INTEGER, allowNull: true },
    is_ps: { type: DataTypes.FLOAT(8, 2), allowNull: true },
    is_ps_thai: { type: DataTypes.FLOAT(8, 2), allowNull: true },
    is_pttype: { type: DataTypes.STRING(4), allowNull: true },
    is_pttype2: { type: DataTypes.STRING(4), allowNull: true },
    is_pttype3: { type: DataTypes.STRING(4), allowNull: true },
    is_acc_id: { type: DataTypes.STRING(7), allowNull: true },
    is_lblind: { type: DataTypes.INTEGER, allowNull: true },
    is_blind1: { type: DataTypes.INTEGER, allowNull: true },
    is_blind2: { type: DataTypes.INTEGER, allowNull: true },
    is_blind3: { type: DataTypes.INTEGER, allowNull: true },
    is_blind4: { type: DataTypes.INTEGER, allowNull: true },
    is_lcost: { type: DataTypes.INTEGER, allowNull: true, comment: 'ค่ารักษาพยาบาล' },
    is_ddate: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่เสียชีวิต' },
    is_recorder: { type: DataTypes.STRING(50), allowNull: true },
    is_recorderipd: { type: DataTypes.STRING(50), allowNull: true },
    is_referhosp: { type: DataTypes.STRING(50), allowNull: true },
    is_referprov: { type: DataTypes.STRING(50), allowNull: true },
    is_dlt: { type: DataTypes.DATE, allowNull: true },
    is_edt: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่ Edit' },
    is_vn: { type: DataTypes.STRING(20), allowNull: true },
    is_lat: { type: DataTypes.STRING(15), allowNull: true, comment: 'latitude จุดเกิดเหตุ' },
    is_lng: { type: DataTypes.STRING(15), allowNull: true, comment: 'longitude จุดเกิดเหตุ' },
    is_incident_id: { type: DataTypes.INTEGER, allowNull: true },
    is_mass_casualty: { type: DataTypes.BOOLEAN, allowNull: true, defaultValue: 0 },
    is_items: { type: DataTypes.STRING(30), allowNull: true, comment: 'เลขที่จากระบบ ITEMS' },
    is_alcohol_check: { type: DataTypes.CHAR(1), allowNull: true, defaultValue: 'N', comment: '1=ตรวจ 2=ไม่ตรวจ N=ไม่ทราบ' },
    is_alcohol_level: { type: DataTypes.INTEGER, allowNull: true },
    is_alcohol_check2: { type: DataTypes.CHAR(1), allowNull: true, defaultValue: 'N', comment: 'ผู้ขับขี่ 1=ตรวจ 2=ไม่ตรวจ N=ไม่ทราบ' },
    is_alcohol_level2: { type: DataTypes.INTEGER, allowNull: true },
    is_alcohol_prove: { type: DataTypes.BOOLEAN, allowNull: true, comment: 'ส่งตรวจ Alcohol' },
    is_alcohol_prove_name: { type: DataTypes.STRING(100), allowNull: true, comment: 'ชื่อผู้ขับขี่อื่นที่รับการตรวจ' },
    is_car_safe: { type: DataTypes.BOOLEAN, allowNull: true, comment: 'ความปลอดภัยของรถ (ปภ.4)' },
    is_license_card: { type: DataTypes.BOOLEAN, allowNull: true, comment: 'ใบขับขี่ (ปภ.4)' },
    is_speed_drive: { type: DataTypes.BOOLEAN, allowNull: true, comment: 'ความเร็ว (ปภ.4)' },
    is_roadsafety: { type: DataTypes.BOOLEAN, allowNull: true, comment: 'สรุปมาตรการ 3ม. 2ข. 1ร. (ปภ.4)' },
    is_refer_result: { type: DataTypes.STRING(50), allowNull: true, comment: 'ผลการรักษา รพ.ที่รับ Refer' },
    is_yearly: { type: DataTypes.INTEGER, allowNull: true, comment: 'ปีงบประมาณ' },
    is_kwd: { type: DataTypes.STRING(20), allowNull: true },
    is_sentmoph: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่ส่งส่วนกลาง' },
    is_version: { type: DataTypes.STRING(20), allowNull: true },
    is_detail: { type: DataTypes.TEXT, allowNull: true, comment: 'รายละเอียดอื่นๆ' },
    is_remark: { type: DataTypes.TEXT, allowNull: true, comment: 'หมายเหตุ' },
    is_his: { type: DataTypes.TEXT, allowNull: true },
    is_dgis: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่ปักมุด' },
    is_dupload: { type: DataTypes.DATE, allowNull: true, comment: 'วันที่ส่งเข้า จ.' },
    is_seq: { type: DataTypes.STRING(20), allowNull: true, comment: 'seq ตามมาตรฐาน hdc' },
    is_pher_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true, comment: 'รหัส ref กรณีมีการส่งไป pher accident' },
    is_inp_src: { type: DataTypes.STRING(20), allowNull: true, comment: 'บันทึกจากระบบ API; ISWIN; PHER; PHER+' },
    is_inp_id: { type: DataTypes.STRING(20), allowNull: true, comment: 'ผู้บันทึก' },
    is_edit_id: { type: DataTypes.STRING(20), allowNull: true, comment: 'ผู้แก้ไข' },
    is_ip: { type: DataTypes.STRING(20), allowNull: true },
    is_lastupdate: { type: DataTypes.DATE, allowNull: true },
    police_vehicle_event_id: { type: DataTypes.STRING(50), allowNull: true },
    police_vehicle_vehicle_index: { type: DataTypes.INTEGER, allowNull: true },
    police_vehicle_vehicle: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_vehicle_plate: { type: DataTypes.STRING(20), allowNull: true },
    police_vehicle_vehicle_province: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_fullname: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_cid: { type: DataTypes.STRING(20), allowNull: true },
    police_vehicle_age: { type: DataTypes.INTEGER, allowNull: true },
    police_vehicle_sex: { type: DataTypes.STRING(10), allowNull: true },
    police_vehicle_nation: { type: DataTypes.STRING(50), allowNull: true },
    police_vehicle_occupation: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_roaduser: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_vehicle_ride_index: { type: DataTypes.INTEGER, allowNull: true },
    police_vehicle_injury: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_alcohol: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_injury_factor: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_belt: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_helmet: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_vehicle_type: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_driving_licence: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_driving_licence_type: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_driving_licence_province: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_prename: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_name: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_lname: { type: DataTypes.STRING(100), allowNull: true },
    police_vehicle_adate: { type: DataTypes.DATEONLY, allowNull: true },
    police_vehicle_project_id: { type: DataTypes.INTEGER, allowNull: true },
    police_vehicle_project_file_id: { type: DataTypes.INTEGER, allowNull: true },
    police_events_event_id: { type: DataTypes.STRING(100), allowNull: true, comment: 'หมายเลขเหตุการณ์' },
    police_events_adate: { type: DataTypes.DATEONLY, allowNull: true, comment: 'วันที่เกิดเหตุ' },
    police_events_atime: { type: DataTypes.STRING(100), allowNull: true, comment: 'เวลาที่เกิดเหตุ' },
    police_events_borchor: { type: DataTypes.STRING(100), allowNull: true, comment: 'บช.' },
    police_events_borkor: { type: DataTypes.STRING(100), allowNull: true, comment: 'บก.' },
    police_events_sornor: { type: DataTypes.STRING(100), allowNull: true, comment: 'สน.' },
    police_events_light: { type: DataTypes.STRING(100), allowNull: true, comment: 'แสงสว่าง' },
    police_events_aroad: { type: DataTypes.STRING(100), allowNull: true, comment: 'ถนนที่เกิดเหตุ' },
    police_events_atumbol: { type: DataTypes.STRING(100), allowNull: true, comment: 'ตำบลที่เกิดเหตุ' },
    police_events_aaumpor: { type: DataTypes.STRING(100), allowNull: true, comment: 'อำเภอที่เกิดเหตุ' },
    police_events_aprovince: { type: DataTypes.STRING(100), allowNull: true, comment: 'จังหวัดที่เกิดเหตุ' },
    police_events_aroad_type: { type: DataTypes.STRING(100), allowNull: true, comment: 'ประเภทถนน' },
    police_events_alane: { type: DataTypes.STRING(100), allowNull: true, comment: 'ลักษณะช่องทาง' },
    police_events_aroad_character: { type: DataTypes.STRING(100), allowNull: true, comment: 'ลักษณะถนน' },
    police_events_aroad_factor: { type: DataTypes.STRING(100), allowNull: true, comment: 'ปัจจัยถนนที่ทำให้' },
    police_events_aroadfit_factor: { type: DataTypes.STRING(100), allowNull: true, comment: 'ปัจจัยจากส่วนควบ' },
    police_events_aenv_factor: { type: DataTypes.STRING(100), allowNull: true, comment: 'ปัจจัยจากสภาพ' },
    police_events_abehavior_factor: { type: DataTypes.STRING(255), allowNull: true, comment: 'พฤติกรรมในการ' },
    police_events_abehavior_other_factor: { type: DataTypes.STRING(255), allowNull: true, comment: 'พฤติกรรมคนเดิน' },
    police_events_avehicle_factor: { type: DataTypes.STRING(255), allowNull: true, comment: 'ปัจจัยจากสภาพรถ' },
    police_events_aconformation: { type: DataTypes.STRING(255), allowNull: true, comment: 'รูปแบบการเกิดอุบัติเหตุ' },
    police_events_vehicle_1: { type: DataTypes.STRING(100), allowNull: true, comment: 'ชนิดรถคันที่ 1' },
    police_events_vehicle_plate_1: { type: DataTypes.STRING(100), allowNull: true, comment: 'ทะเบียนรถคันที่ 1' },
    police_events_vehicle_province_1: { type: DataTypes.STRING(100), allowNull: true, comment: 'จังหวัดทะเบียนรถ' },
    police_events_vehicle_2: { type: DataTypes.STRING(100), allowNull: true, comment: 'ชนิดรถคันที่ 2' },
    police_events_vehicle_plate_2: { type: DataTypes.STRING(30), allowNull: true, comment: 'ทะเบียนรถคันที่ 2' },
    police_events_vehicle_province_2: { type: DataTypes.STRING(100), allowNull: true, comment: 'จังหวัดทะเบียนรถคันที่ 2' },
    police_events_vehicle_3: { type: DataTypes.STRING(100), allowNull: true, comment: 'ชนิดรถคันที่ 3' },
    police_events_vehicle_plate_3: { type: DataTypes.STRING(30), allowNull: true, comment: 'ทะเบียนรถคันที่ 3' },
    police_events_vehicle_province_3: { type: DataTypes.STRING(100), allowNull: true, comment: 'จังหวัดทะเบียนรถคันที่ 3' },
    police_events_vehicle_4: { type: DataTypes.STRING(100), allowNull: true, comment: 'ชนิดรถคันที่ 4' },
    police_events_vehicle_plate_4: { type: DataTypes.STRING(30), allowNull: true, comment: 'ทะเบียนรถคันที่ 4' },
    police_events_vehicle_province_4: { type: DataTypes.STRING(100), allowNull: true, comment: 'จังหวัดทะเบียนรถคันที่ 4' },
    police_events_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
    police_events_project_file_id: { type: DataTypes.INTEGER, allowNull: true },
    police_events_project_id: { type: DataTypes.INTEGER, allowNull: true },
    eclaim_cid: { type: DataTypes.STRING(20), allowNull: true },
    eclaim_vehicle_plate_province: { type: DataTypes.STRING(30), allowNull: true },
    eclaim_vehicle_plate: { type: DataTypes.STRING(30), allowNull: true },
    eclaim_vehicle_type: { type: DataTypes.STRING(255), allowNull: true },
    eclaim_prename: { type: DataTypes.STRING(20), allowNull: true },
    eclaim_name: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_lname: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_gender: { type: DataTypes.STRING(10), allowNull: true },
    eclaim_nation: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_birthdate: { type: DataTypes.DATEONLY, allowNull: true },
    eclaim_age: { type: DataTypes.INTEGER, allowNull: true },
    eclaim_adate: { type: DataTypes.DATE, allowNull: true },
    eclaim_atime: { type: DataTypes.STRING(10), allowNull: true },
    eclaim_atumbol: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_aaumpor: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_aprovince: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_alat: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_along: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_crash_desc: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_occupation: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_address_aumpor: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_address_province: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_hospcode: { type: DataTypes.STRING(10), allowNull: true },
    eclaim_injury_status: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_ride_status: { type: DataTypes.STRING(100), allowNull: true },
    eclaim_cost: { type: DataTypes.INTEGER, allowNull: true },
    eclaim_updated_at: { type: DataTypes.DATE, allowNull: true },
    eclaim_adatetime: { type: DataTypes.DATE, allowNull: true },
    eclaim_created_at: { type: DataTypes.DATE, allowNull: true },
    eclaim_project_id: { type: DataTypes.INTEGER, allowNull: true },
    eclaim_project_file_id: { type: DataTypes.INTEGER, allowNull: true },
    project_id: { type: DataTypes.INTEGER, allowNull: true },
    url_video: { type: DataTypes.STRING(255), allowNull: true },
    uuid: { type: DataTypes.BIGINT, allowNull: true },
    ems_id: { type: DataTypes.INTEGER, allowNull: true },
    ems_incident_number: { type: DataTypes.TEXT, allowNull: true },
    ems_notification_time: { type: DataTypes.DATE, allowNull: true },
    ems_province_code: { type: DataTypes.TEXT, allowNull: true },
    ems_center_code: { type: DataTypes.TEXT, allowNull: true },
    ems_district: { type: DataTypes.TEXT, allowNull: true },
    ems_sub_district: { type: DataTypes.TEXT, allowNull: true },
    ems_latitude: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    ems_longitude: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    ems_scene_location: { type: DataTypes.TEXT, allowNull: true },
    ems_severity_code: { type: DataTypes.TEXT, allowNull: true },
    ems_incident_event: { type: DataTypes.TEXT, allowNull: true },
    ems_patient_number: { type: DataTypes.TEXT, allowNull: true },
    ems_ipd_event_number: { type: DataTypes.TEXT, allowNull: true },
    ems_id_card_number: { type: DataTypes.TEXT, allowNull: true },
    ems_patient_sequence: { type: DataTypes.TEXT, allowNull: true },
    ems_patient_id: { type: DataTypes.TEXT, allowNull: true },
    ems_title: { type: DataTypes.TEXT, allowNull: true },
    ems_first_name: { type: DataTypes.TEXT, allowNull: true },
    ems_last_name: { type: DataTypes.TEXT, allowNull: true },
    ems_gender: { type: DataTypes.TEXT, allowNull: true },
    ems_age_years: { type: DataTypes.TEXT, allowNull: true },
    ems_age_months: { type: DataTypes.TEXT, allowNull: true },
    ems_patient_type: { type: DataTypes.TEXT, allowNull: true },
    ems_nationality: { type: DataTypes.TEXT, allowNull: true },
    ems_passport_number: { type: DataTypes.TEXT, allowNull: true },
    ems_treatment_right: { type: DataTypes.TEXT, allowNull: true },
    ems_other_insurance: { type: DataTypes.TEXT, allowNull: true },
    ems_country: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_type: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_plate_category: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_plate_number: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_province: { type: DataTypes.TEXT, allowNull: true },
    ems_delivery_province: { type: DataTypes.TEXT, allowNull: true },
    ems_hospital: { type: DataTypes.TEXT, allowNull: true },
    ems_hospital_type: { type: DataTypes.TEXT, allowNull: true },
    ems_delivery_time: { type: DataTypes.TEXT, allowNull: true },
    ems_triage_level: { type: DataTypes.TEXT, allowNull: true },
    ems_operation_number: { type: DataTypes.TEXT, allowNull: true },
    ems_operation_event_number: { type: DataTypes.TEXT, allowNull: true },
    ems_command_time: { type: DataTypes.TEXT, allowNull: true },
    ems_unit_level: { type: DataTypes.TEXT, allowNull: true },
    ems_time_unit_notified: { type: DataTypes.TEXT, allowNull: true },
    ems_time_left_base: { type: DataTypes.TEXT, allowNull: true },
    ems_lat_left_base: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    ems_long_left_base: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    ems_time_arrived_scene: { type: DataTypes.TEXT, allowNull: true },
    ems_time_left_scene: { type: DataTypes.TEXT, allowNull: true },
    ems_lat_scene: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    ems_long_scene: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    ems_time_arrived_hospital: { type: DataTypes.TEXT, allowNull: true },
    ems_lat_hospital: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    ems_long_hospital: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    ems_time_arrived_base: { type: DataTypes.TEXT, allowNull: true },
    ems_lat_base: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    ems_long_base: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    ems_idc_code_scene: { type: DataTypes.TEXT, allowNull: true },
    ems_operation_status: { type: DataTypes.TEXT, allowNull: true },
    ems_operation_option: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_plate_cat_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_plate_num_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_province_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    ems_vehicle_owner_symptom_25: { type: DataTypes.TEXT, allowNull: true },
    ems_system_status: { type: DataTypes.TEXT, allowNull: true },
    ems_recorder_name: { type: DataTypes.TEXT, allowNull: true },
    ems_patient_type_2: { type: DataTypes.TEXT, allowNull: true },
    ems_consciousness: { type: DataTypes.TEXT, allowNull: true },
    ems_breathing: { type: DataTypes.TEXT, allowNull: true },
    ems_wound: { type: DataTypes.TEXT, allowNull: true },
    ems_deformity: { type: DataTypes.TEXT, allowNull: true },
    ems_organ: { type: DataTypes.TEXT, allowNull: true },
    ems_airway: { type: DataTypes.TEXT, allowNull: true },
    ems_stop_bleeding: { type: DataTypes.TEXT, allowNull: true },
    ems_splinting: { type: DataTypes.TEXT, allowNull: true },
    ems_fluids: { type: DataTypes.TEXT, allowNull: true },
    ems_fluids_detail: { type: DataTypes.TEXT, allowNull: true },
    ems_cpr: { type: DataTypes.TEXT, allowNull: true },
    ems_medication: { type: DataTypes.TEXT, allowNull: true },
    ems_initial_care_result: { type: DataTypes.TEXT, allowNull: true },
    ems_wound_2: { type: DataTypes.TEXT, allowNull: true },
    ems_deformity_2: { type: DataTypes.TEXT, allowNull: true },
    ems_blood_loss: { type: DataTypes.TEXT, allowNull: true },
    ems_organ_2: { type: DataTypes.TEXT, allowNull: true },
    ems_medicine_method: { type: DataTypes.TEXT, allowNull: true },
    ems_medicine_detail: { type: DataTypes.TEXT, allowNull: true },
    ems_obgyn: { type: DataTypes.TEXT, allowNull: true },
    ems_obgyn_detail: { type: DataTypes.TEXT, allowNull: true },
    ems_pediatrics: { type: DataTypes.TEXT, allowNull: true },
    ems_pediatrics_detail: { type: DataTypes.TEXT, allowNull: true },
    ems_surgery: { type: DataTypes.TEXT, allowNull: true },
    ems_surgery_detail: { type: DataTypes.TEXT, allowNull: true },
    ems_others: { type: DataTypes.TEXT, allowNull: true },
    ems_diagnosis: { type: DataTypes.TEXT, allowNull: true },
    ems_airway_2: { type: DataTypes.TEXT, allowNull: true },
    ems_stop_bleeding_2: { type: DataTypes.TEXT, allowNull: true },
    ems_splinting_2: { type: DataTypes.TEXT, allowNull: true },
    ems_fluids_2: { type: DataTypes.TEXT, allowNull: true },
    ems_admitted: { type: DataTypes.TEXT, allowNull: true },
    ems_treatment_result: { type: DataTypes.TEXT, allowNull: true },
    ems_vital_signs: { type: DataTypes.TEXT, allowNull: true },
    ems_neuro_signs: { type: DataTypes.TEXT, allowNull: true },
    ems_pupils: { type: DataTypes.TEXT, allowNull: true },
    ems_o2_sat: { type: DataTypes.TEXT, allowNull: true },
    ems_dtx: { type: DataTypes.TEXT, allowNull: true },

    rsis_id: { type: DataTypes.INTEGER },
    rsis_protocal: { type: DataTypes.STRING(255) },
}, {
    sequelize: dbServer,
    modelName: 'IntegrateFinalFullEMS',
    tableName: 'integrate_final_full_ems',
    timestamps: true,
    createdAt: 'created_at',
    updatedAt: 'updated_at',
    underscored: true,
    freezeTableName: true,
    indexes: [
        { name: 'idx_injury_date', using: 'BTREE', fields: ['injury_date'] },
        { name: 'idx_aprovince_code', using: 'BTREE', fields: ['aprovince_code'] },
        { name: 'idx_project_id', using: 'BTREE', fields: ['project_id'] },
        { name: 'idx_area_code', using: 'BTREE', fields: ['area_code'] },
        { name: 'idx_aaumpor_code', using: 'BTREE', fields: ['aaumpor_code'] },
        { name: 'idx_vehicle_1', using: 'BTREE', fields: ['vehicle_1'] },
        { name: 'idx_aaumpor', using: 'BTREE', fields: ['aaumpor'] },
        { name: 'idx_aprovince', using: 'BTREE', fields: ['aprovince'] },
        { name: 'idx_admit_death', using: 'BTREE', fields: ['admit', 'is_death'] },
        { name: 'idx_accdate_aprovince_admit_death', using: 'BTREE', fields: ['accdate', 'aprovince', 'admit', 'is_death'] },
        { name: 'idx_age_gender', using: 'BTREE', fields: ['age', 'gender'] },
        { name: 'idx_accdate', using: 'BTREE', fields: ['accdate'] },
        { name: 'idx_injury_vehicle', using: 'BTREE', fields: ['injury_date', 'vehicle_1'] },
        { name: 'idx_vehicle_belt', using: 'BTREE', fields: ['vehicle_1', 'belt_risk'] },
        { name: 'idx_vehicle_helmet', using: 'BTREE', fields: ['vehicle_1', 'helmet_risk'] },
        { name: 'idx_roaduser_alcohol', using: 'BTREE', fields: ['roaduser', 'alcohol'] },
        { name: 'idx_injury_ids', using: 'BTREE', fields: ['injury_date', 'is_id', 'his_id', 'eclaim_id', 'police_id'] },
        { name: 'idx_injury_aprovince_death_admit', using: 'BTREE', fields: ['injury_date', 'aprovince', 'admit', 'is_death'] },
        { name: 'idx_injury_province_district', using: 'BTREE', fields: ['injury_date', 'aprovince', 'aaumpor', 'admit', 'is_death'] },
        { name: 'idx_injury_date_province_area_code', using: 'BTREE', fields: ['injury_date', 'aprovince_code', 'aprovince', 'area_code'] },
        { name: 'idx_injury_date_age_area_code', using: 'BTREE', fields: ['injury_date', 'age', 'area_code'] },
        { name: 'idx_injury_date_accdate_area_code', using: 'BTREE', fields: ['injury_date', 'accdate', 'area_code'] },
        { name: 'idx_injury_date_gender_area_code', using: 'BTREE', fields: ['injury_date', 'gender', 'area_code'] },
        { name: 'idx_injury_date_vehicle1_area_code', using: 'BTREE', fields: ['injury_date', 'vehicle_1', 'area_code'] },
        { name: 'idx_injury_date_roaduser_area_code', using: 'BTREE', fields: ['injury_date', 'roaduser', 'area_code'] }
    ]
});

module.exports = IntegrateFinalFullEMS;
