const { Sequelize, DataTypes, Model } = require('sequelize');
const dbServer = require('../../../config/connections/db_server_raw'); // Ensure this path is correct for your project
class HIS extends Model {}

HIS.init({
    id: { type: DataTypes.INTEGER, allowNull: false, primaryKey: true, autoIncrement: true },
    PID: { type: DataTypes.STRING, allowNull: true },
    HOSPCODE: { type: DataTypes.STRING, allowNull: true },
    DATE_SERV: { type: DataTypes.DATE, allowNull: true },
    SEQ: { type: DataTypes.STRING, allowNull: true },
    AN: { type: DataTypes.STRING, allowNull: true },
    DIAGCODE: { type: DataTypes.STRING, allowNull: true },
    ISDEATH: { type: DataTypes.TINYINT, allowNull: true },
    CDEATH: { type: DataTypes.STRING, allowNull: true },
    Price: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
    PAYPRICE: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
    ACTUALPAY: { type: DataTypes.DECIMAL(10, 2), allowNull: true },
    DATEINHOSP: { type: DataTypes.TINYINT, allowNull: true },
    CID: { type: DataTypes.STRING, allowNull: true },
    NAME: { type: DataTypes.STRING, allowNull: true },
    LNAME: { type: DataTypes.STRING, allowNull: true },
    sex: { type: DataTypes.TINYINT, allowNull: true },
    NATION: { type: DataTypes.STRING, allowNull: true },
    BIRTH: { type: DataTypes.DATE, allowNull: true },
    AGE: { type: DataTypes.INTEGER, allowNull: true },
    OPD_CODE: { type: DataTypes.TEXT, allowNull: true },
    IPD_CODE: { type: DataTypes.TEXT, allowNull: true },
    ALLCODE: { type: DataTypes.TEXT, allowNull: true },
    S0: { type: DataTypes.TINYINT, allowNull: true },
    S1: { type: DataTypes.TINYINT, allowNull: true },
    S2: { type: DataTypes.TINYINT, allowNull: true },
    S3: { type: DataTypes.TINYINT, allowNull: true },
    S4: { type: DataTypes.TINYINT, allowNull: true },
    S5: { type: DataTypes.TINYINT, allowNull: true },
    S6: { type: DataTypes.TINYINT, allowNull: true },
    S7: { type: DataTypes.TINYINT, allowNull: true },
    S8: { type: DataTypes.TINYINT, allowNull: true },
    S9: { type: DataTypes.TINYINT, allowNull: true },
    AEPLACE: { type: DataTypes.STRING, allowNull: true },
    AETYPE: { type: DataTypes.STRING, allowNull: true },
    AIRWAY: { type: DataTypes.TINYINT, allowNull: true },
    ALCOHOL: { type: DataTypes.TINYINT, allowNull: true },
    SPLINT: { type: DataTypes.TINYINT, allowNull: true },
    BELT: { type: DataTypes.TINYINT, allowNull: true },
    HELMET: { type: DataTypes.TINYINT, allowNull: true },
    COMA_EYE: { type: DataTypes.TINYINT, allowNull: true },
    COMA_MOVEMENT: { type: DataTypes.TINYINT, allowNull: true },
    COMA_SPEAK: { type: DataTypes.TINYINT, allowNull: true },
    NACROTIC_DRUG: { type: DataTypes.TINYINT, allowNull: true },
    STOPBLEED: { type: DataTypes.TINYINT, allowNull: true },
    TRAFFIC: { type: DataTypes.TINYINT, allowNull: true },
    TYPEIN_AE: { type: DataTypes.TINYINT, allowNull: true },
    URGENCY: { type: DataTypes.TINYINT, allowNull: true },
    VEHICLE: { type: DataTypes.STRING, allowNull: true },
    created_at: { type: DataTypes.DATE, allowNull: true },
    updated_at: { type: DataTypes.DATE, allowNull: true },
    province_id: { type: DataTypes.INTEGER, allowNull: true }
}, {
    sequelize: dbServer,
    modelName: 'HisRecord',
    tableName: 'hdc_records',
    underscored: false,
    createdAt: 'created_at',
    updatedAt: 'updated_at'
});

module.exports = HIS;
